### PR TITLE
Feature observer

### PR DESCRIPTION
**Pull request by LaraMo**
Note, the grand schema of the observer pattern has been completed. All left to do is to implement it once all the needed classes are merged. 

// TODO: when merged
// CommandProcessor::saveCommand()
// Command::saveEffect()
// Order::execute() --> DONE, BUT THE EFFECT ISNT READY, SO NEED TO ADD IT WHEN WE MERGE
// OrderList::addOrder()
// GameEngine::transition()

//todo: extend the following classes when merged:
// Order - DONE 
// OrderList
// GameEngine 
// Command
// CommandProcessor

### CODE REVIEW

**Comment by EyalAzimov** [comment]
you wrote Order-DONE, does that mean you merged with orders-excution branch?

**Comment by LaraMo** [comment]
@EyalAzimov not quite, its means that when an order was created, the observer pattern was hooked up properly to observe such event.
image


once you merge, it will need to call `notify(this)` in the proper method. See comment:
// Order::execute() --> DONE, BUT THE EFFECT ISNT READY, SO NEED TO ADD IT WHEN WE MERGE

**Review by EyalAzimov — APPROVED** [review]
Great work! 
Matches what the assignment wants in the diagram and description!
Very easy to understand!

**Review by kontacky01 — COMMENTED** [review]
pretty neat Lara! good job :))

**Pull request merged**
